// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tap/v1/admin.proto

package tapv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/evalops/siphon/proto/tap/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TapAdminServiceName is the fully-qualified name of the TapAdminService service.
	TapAdminServiceName = "tap.v1.TapAdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TapAdminServiceListReplayJobsProcedure is the fully-qualified name of the TapAdminService's
	// ListReplayJobs RPC.
	TapAdminServiceListReplayJobsProcedure = "/tap.v1.TapAdminService/ListReplayJobs"
	// TapAdminServiceEnqueueReplayJobProcedure is the fully-qualified name of the TapAdminService's
	// EnqueueReplayJob RPC.
	TapAdminServiceEnqueueReplayJobProcedure = "/tap.v1.TapAdminService/EnqueueReplayJob"
	// TapAdminServiceGetReplayJobProcedure is the fully-qualified name of the TapAdminService's
	// GetReplayJob RPC.
	TapAdminServiceGetReplayJobProcedure = "/tap.v1.TapAdminService/GetReplayJob"
	// TapAdminServiceCancelReplayJobProcedure is the fully-qualified name of the TapAdminService's
	// CancelReplayJob RPC.
	TapAdminServiceCancelReplayJobProcedure = "/tap.v1.TapAdminService/CancelReplayJob"
	// TapAdminServiceGetPollerStatusProcedure is the fully-qualified name of the TapAdminService's
	// GetPollerStatus RPC.
	TapAdminServiceGetPollerStatusProcedure = "/tap.v1.TapAdminService/GetPollerStatus"
)

// TapAdminServiceClient is a client for the tap.v1.TapAdminService service.
type TapAdminServiceClient interface {
	ListReplayJobs(context.Context, *connect.Request[v1.ListReplayJobsRequest]) (*connect.Response[v1.ListReplayJobsResponse], error)
	EnqueueReplayJob(context.Context, *connect.Request[v1.EnqueueReplayJobRequest]) (*connect.Response[v1.EnqueueReplayJobResponse], error)
	GetReplayJob(context.Context, *connect.Request[v1.GetReplayJobRequest]) (*connect.Response[v1.GetReplayJobResponse], error)
	CancelReplayJob(context.Context, *connect.Request[v1.CancelReplayJobRequest]) (*connect.Response[v1.CancelReplayJobResponse], error)
	GetPollerStatus(context.Context, *connect.Request[v1.GetPollerStatusRequest]) (*connect.Response[v1.GetPollerStatusResponse], error)
}

// NewTapAdminServiceClient constructs a client for the tap.v1.TapAdminService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTapAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TapAdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tapAdminServiceMethods := v1.File_tap_v1_admin_proto.Services().ByName("TapAdminService").Methods()
	return &tapAdminServiceClient{
		listReplayJobs: connect.NewClient[v1.ListReplayJobsRequest, v1.ListReplayJobsResponse](
			httpClient,
			baseURL+TapAdminServiceListReplayJobsProcedure,
			connect.WithSchema(tapAdminServiceMethods.ByName("ListReplayJobs")),
			connect.WithClientOptions(opts...),
		),
		enqueueReplayJob: connect.NewClient[v1.EnqueueReplayJobRequest, v1.EnqueueReplayJobResponse](
			httpClient,
			baseURL+TapAdminServiceEnqueueReplayJobProcedure,
			connect.WithSchema(tapAdminServiceMethods.ByName("EnqueueReplayJob")),
			connect.WithClientOptions(opts...),
		),
		getReplayJob: connect.NewClient[v1.GetReplayJobRequest, v1.GetReplayJobResponse](
			httpClient,
			baseURL+TapAdminServiceGetReplayJobProcedure,
			connect.WithSchema(tapAdminServiceMethods.ByName("GetReplayJob")),
			connect.WithClientOptions(opts...),
		),
		cancelReplayJob: connect.NewClient[v1.CancelReplayJobRequest, v1.CancelReplayJobResponse](
			httpClient,
			baseURL+TapAdminServiceCancelReplayJobProcedure,
			connect.WithSchema(tapAdminServiceMethods.ByName("CancelReplayJob")),
			connect.WithClientOptions(opts...),
		),
		getPollerStatus: connect.NewClient[v1.GetPollerStatusRequest, v1.GetPollerStatusResponse](
			httpClient,
			baseURL+TapAdminServiceGetPollerStatusProcedure,
			connect.WithSchema(tapAdminServiceMethods.ByName("GetPollerStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tapAdminServiceClient implements TapAdminServiceClient.
type tapAdminServiceClient struct {
	listReplayJobs   *connect.Client[v1.ListReplayJobsRequest, v1.ListReplayJobsResponse]
	enqueueReplayJob *connect.Client[v1.EnqueueReplayJobRequest, v1.EnqueueReplayJobResponse]
	getReplayJob     *connect.Client[v1.GetReplayJobRequest, v1.GetReplayJobResponse]
	cancelReplayJob  *connect.Client[v1.CancelReplayJobRequest, v1.CancelReplayJobResponse]
	getPollerStatus  *connect.Client[v1.GetPollerStatusRequest, v1.GetPollerStatusResponse]
}

// ListReplayJobs calls tap.v1.TapAdminService.ListReplayJobs.
func (c *tapAdminServiceClient) ListReplayJobs(ctx context.Context, req *connect.Request[v1.ListReplayJobsRequest]) (*connect.Response[v1.ListReplayJobsResponse], error) {
	return c.listReplayJobs.CallUnary(ctx, req)
}

// EnqueueReplayJob calls tap.v1.TapAdminService.EnqueueReplayJob.
func (c *tapAdminServiceClient) EnqueueReplayJob(ctx context.Context, req *connect.Request[v1.EnqueueReplayJobRequest]) (*connect.Response[v1.EnqueueReplayJobResponse], error) {
	return c.enqueueReplayJob.CallUnary(ctx, req)
}

// GetReplayJob calls tap.v1.TapAdminService.GetReplayJob.
func (c *tapAdminServiceClient) GetReplayJob(ctx context.Context, req *connect.Request[v1.GetReplayJobRequest]) (*connect.Response[v1.GetReplayJobResponse], error) {
	return c.getReplayJob.CallUnary(ctx, req)
}

// CancelReplayJob calls tap.v1.TapAdminService.CancelReplayJob.
func (c *tapAdminServiceClient) CancelReplayJob(ctx context.Context, req *connect.Request[v1.CancelReplayJobRequest]) (*connect.Response[v1.CancelReplayJobResponse], error) {
	return c.cancelReplayJob.CallUnary(ctx, req)
}

// GetPollerStatus calls tap.v1.TapAdminService.GetPollerStatus.
func (c *tapAdminServiceClient) GetPollerStatus(ctx context.Context, req *connect.Request[v1.GetPollerStatusRequest]) (*connect.Response[v1.GetPollerStatusResponse], error) {
	return c.getPollerStatus.CallUnary(ctx, req)
}

// TapAdminServiceHandler is an implementation of the tap.v1.TapAdminService service.
type TapAdminServiceHandler interface {
	ListReplayJobs(context.Context, *connect.Request[v1.ListReplayJobsRequest]) (*connect.Response[v1.ListReplayJobsResponse], error)
	EnqueueReplayJob(context.Context, *connect.Request[v1.EnqueueReplayJobRequest]) (*connect.Response[v1.EnqueueReplayJobResponse], error)
	GetReplayJob(context.Context, *connect.Request[v1.GetReplayJobRequest]) (*connect.Response[v1.GetReplayJobResponse], error)
	CancelReplayJob(context.Context, *connect.Request[v1.CancelReplayJobRequest]) (*connect.Response[v1.CancelReplayJobResponse], error)
	GetPollerStatus(context.Context, *connect.Request[v1.GetPollerStatusRequest]) (*connect.Response[v1.GetPollerStatusResponse], error)
}

// NewTapAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTapAdminServiceHandler(svc TapAdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tapAdminServiceMethods := v1.File_tap_v1_admin_proto.Services().ByName("TapAdminService").Methods()
	tapAdminServiceListReplayJobsHandler := connect.NewUnaryHandler(
		TapAdminServiceListReplayJobsProcedure,
		svc.ListReplayJobs,
		connect.WithSchema(tapAdminServiceMethods.ByName("ListReplayJobs")),
		connect.WithHandlerOptions(opts...),
	)
	tapAdminServiceEnqueueReplayJobHandler := connect.NewUnaryHandler(
		TapAdminServiceEnqueueReplayJobProcedure,
		svc.EnqueueReplayJob,
		connect.WithSchema(tapAdminServiceMethods.ByName("EnqueueReplayJob")),
		connect.WithHandlerOptions(opts...),
	)
	tapAdminServiceGetReplayJobHandler := connect.NewUnaryHandler(
		TapAdminServiceGetReplayJobProcedure,
		svc.GetReplayJob,
		connect.WithSchema(tapAdminServiceMethods.ByName("GetReplayJob")),
		connect.WithHandlerOptions(opts...),
	)
	tapAdminServiceCancelReplayJobHandler := connect.NewUnaryHandler(
		TapAdminServiceCancelReplayJobProcedure,
		svc.CancelReplayJob,
		connect.WithSchema(tapAdminServiceMethods.ByName("CancelReplayJob")),
		connect.WithHandlerOptions(opts...),
	)
	tapAdminServiceGetPollerStatusHandler := connect.NewUnaryHandler(
		TapAdminServiceGetPollerStatusProcedure,
		svc.GetPollerStatus,
		connect.WithSchema(tapAdminServiceMethods.ByName("GetPollerStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tap.v1.TapAdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TapAdminServiceListReplayJobsProcedure:
			tapAdminServiceListReplayJobsHandler.ServeHTTP(w, r)
		case TapAdminServiceEnqueueReplayJobProcedure:
			tapAdminServiceEnqueueReplayJobHandler.ServeHTTP(w, r)
		case TapAdminServiceGetReplayJobProcedure:
			tapAdminServiceGetReplayJobHandler.ServeHTTP(w, r)
		case TapAdminServiceCancelReplayJobProcedure:
			tapAdminServiceCancelReplayJobHandler.ServeHTTP(w, r)
		case TapAdminServiceGetPollerStatusProcedure:
			tapAdminServiceGetPollerStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTapAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTapAdminServiceHandler struct{}

func (UnimplementedTapAdminServiceHandler) ListReplayJobs(context.Context, *connect.Request[v1.ListReplayJobsRequest]) (*connect.Response[v1.ListReplayJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tap.v1.TapAdminService.ListReplayJobs is not implemented"))
}

func (UnimplementedTapAdminServiceHandler) EnqueueReplayJob(context.Context, *connect.Request[v1.EnqueueReplayJobRequest]) (*connect.Response[v1.EnqueueReplayJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tap.v1.TapAdminService.EnqueueReplayJob is not implemented"))
}

func (UnimplementedTapAdminServiceHandler) GetReplayJob(context.Context, *connect.Request[v1.GetReplayJobRequest]) (*connect.Response[v1.GetReplayJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tap.v1.TapAdminService.GetReplayJob is not implemented"))
}

func (UnimplementedTapAdminServiceHandler) CancelReplayJob(context.Context, *connect.Request[v1.CancelReplayJobRequest]) (*connect.Response[v1.CancelReplayJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tap.v1.TapAdminService.CancelReplayJob is not implemented"))
}

func (UnimplementedTapAdminServiceHandler) GetPollerStatus(context.Context, *connect.Request[v1.GetPollerStatusRequest]) (*connect.Response[v1.GetPollerStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tap.v1.TapAdminService.GetPollerStatus is not implemented"))
}
