// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tap/v1/admin.proto

package tapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplayJobStatus int32

const (
	ReplayJobStatus_REPLAY_JOB_STATUS_UNSPECIFIED ReplayJobStatus = 0
	ReplayJobStatus_REPLAY_JOB_STATUS_QUEUED      ReplayJobStatus = 1
	ReplayJobStatus_REPLAY_JOB_STATUS_RUNNING     ReplayJobStatus = 2
	ReplayJobStatus_REPLAY_JOB_STATUS_SUCCEEDED   ReplayJobStatus = 3
	ReplayJobStatus_REPLAY_JOB_STATUS_FAILED      ReplayJobStatus = 4
	ReplayJobStatus_REPLAY_JOB_STATUS_CANCELLED   ReplayJobStatus = 5
)

// Enum value maps for ReplayJobStatus.
var (
	ReplayJobStatus_name = map[int32]string{
		0: "REPLAY_JOB_STATUS_UNSPECIFIED",
		1: "REPLAY_JOB_STATUS_QUEUED",
		2: "REPLAY_JOB_STATUS_RUNNING",
		3: "REPLAY_JOB_STATUS_SUCCEEDED",
		4: "REPLAY_JOB_STATUS_FAILED",
		5: "REPLAY_JOB_STATUS_CANCELLED",
	}
	ReplayJobStatus_value = map[string]int32{
		"REPLAY_JOB_STATUS_UNSPECIFIED": 0,
		"REPLAY_JOB_STATUS_QUEUED":      1,
		"REPLAY_JOB_STATUS_RUNNING":     2,
		"REPLAY_JOB_STATUS_SUCCEEDED":   3,
		"REPLAY_JOB_STATUS_FAILED":      4,
		"REPLAY_JOB_STATUS_CANCELLED":   5,
	}
)

func (x ReplayJobStatus) Enum() *ReplayJobStatus {
	p := new(ReplayJobStatus)
	*p = x
	return p
}

func (x ReplayJobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplayJobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tap_v1_admin_proto_enumTypes[0].Descriptor()
}

func (ReplayJobStatus) Type() protoreflect.EnumType {
	return &file_tap_v1_admin_proto_enumTypes[0]
}

func (x ReplayJobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplayJobStatus.Descriptor instead.
func (ReplayJobStatus) EnumDescriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{0}
}

type ReplayJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         ReplayJobStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=tap.v1.ReplayJobStatus" json:"status,omitempty"`
	RequestedLimit int32                  `protobuf:"varint,3,opt,name=requested_limit,json=requestedLimit,proto3" json:"requested_limit,omitempty"`
	EffectiveLimit int32                  `protobuf:"varint,4,opt,name=effective_limit,json=effectiveLimit,proto3" json:"effective_limit,omitempty"`
	MaxLimit       int32                  `protobuf:"varint,5,opt,name=max_limit,json=maxLimit,proto3" json:"max_limit,omitempty"`
	Capped         bool                   `protobuf:"varint,6,opt,name=capped,proto3" json:"capped,omitempty"`
	DryRun         bool                   `protobuf:"varint,7,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Replayed       int32                  `protobuf:"varint,11,opt,name=replayed,proto3" json:"replayed,omitempty"`
	RequestId      string                 `protobuf:"bytes,12,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OperatorReason string                 `protobuf:"bytes,13,opt,name=operator_reason,json=operatorReason,proto3" json:"operator_reason,omitempty"`
	CancelReason   string                 `protobuf:"bytes,14,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	Error          string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayJob) Reset() {
	*x = ReplayJob{}
	mi := &file_tap_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayJob) ProtoMessage() {}

func (x *ReplayJob) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayJob.ProtoReflect.Descriptor instead.
func (*ReplayJob) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReplayJob) GetStatus() ReplayJobStatus {
	if x != nil {
		return x.Status
	}
	return ReplayJobStatus_REPLAY_JOB_STATUS_UNSPECIFIED
}

func (x *ReplayJob) GetRequestedLimit() int32 {
	if x != nil {
		return x.RequestedLimit
	}
	return 0
}

func (x *ReplayJob) GetEffectiveLimit() int32 {
	if x != nil {
		return x.EffectiveLimit
	}
	return 0
}

func (x *ReplayJob) GetMaxLimit() int32 {
	if x != nil {
		return x.MaxLimit
	}
	return 0
}

func (x *ReplayJob) GetCapped() bool {
	if x != nil {
		return x.Capped
	}
	return false
}

func (x *ReplayJob) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ReplayJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReplayJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReplayJob) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ReplayJob) GetReplayed() int32 {
	if x != nil {
		return x.Replayed
	}
	return 0
}

func (x *ReplayJob) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReplayJob) GetOperatorReason() string {
	if x != nil {
		return x.OperatorReason
	}
	return ""
}

func (x *ReplayJob) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *ReplayJob) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReplayJobStatusCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReplayJobStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=tap.v1.ReplayJobStatus" json:"status,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayJobStatusCount) Reset() {
	*x = ReplayJobStatusCount{}
	mi := &file_tap_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayJobStatusCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayJobStatusCount) ProtoMessage() {}

func (x *ReplayJobStatusCount) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayJobStatusCount.ProtoReflect.Descriptor instead.
func (*ReplayJobStatusCount) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ReplayJobStatusCount) GetStatus() ReplayJobStatus {
	if x != nil {
		return x.Status
	}
	return ReplayJobStatus_REPLAY_JOB_STATUS_UNSPECIFIED
}

func (x *ReplayJobStatusCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListReplayJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReplayJobStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=tap.v1.ReplayJobStatus" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplayJobsRequest) Reset() {
	*x = ListReplayJobsRequest{}
	mi := &file_tap_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplayJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplayJobsRequest) ProtoMessage() {}

func (x *ListReplayJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplayJobsRequest.ProtoReflect.Descriptor instead.
func (*ListReplayJobsRequest) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListReplayJobsRequest) GetStatus() ReplayJobStatus {
	if x != nil {
		return x.Status
	}
	return ReplayJobStatus_REPLAY_JOB_STATUS_UNSPECIFIED
}

func (x *ListReplayJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReplayJobsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListReplayJobsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RequestId     string                  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        ReplayJobStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=tap.v1.ReplayJobStatus" json:"status,omitempty"`
	Limit         int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                  `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	NextCursor    string                  `protobuf:"bytes,5,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Count         int32                   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	Summary       []*ReplayJobStatusCount `protobuf:"bytes,7,rep,name=summary,proto3" json:"summary,omitempty"`
	Jobs          []*ReplayJob            `protobuf:"bytes,8,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReplayJobsResponse) Reset() {
	*x = ListReplayJobsResponse{}
	mi := &file_tap_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReplayJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReplayJobsResponse) ProtoMessage() {}

func (x *ListReplayJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReplayJobsResponse.ProtoReflect.Descriptor instead.
func (*ListReplayJobsResponse) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListReplayJobsResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListReplayJobsResponse) GetStatus() ReplayJobStatus {
	if x != nil {
		return x.Status
	}
	return ReplayJobStatus_REPLAY_JOB_STATUS_UNSPECIFIED
}

func (x *ListReplayJobsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReplayJobsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListReplayJobsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListReplayJobsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListReplayJobsResponse) GetSummary() []*ReplayJobStatusCount {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ListReplayJobsResponse) GetJobs() []*ReplayJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type EnqueueReplayJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	DryRun         bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AdminReason    string                 `protobuf:"bytes,4,opt,name=admin_reason,json=adminReason,proto3" json:"admin_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueReplayJobRequest) Reset() {
	*x = EnqueueReplayJobRequest{}
	mi := &file_tap_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueReplayJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueReplayJobRequest) ProtoMessage() {}

func (x *EnqueueReplayJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueReplayJobRequest.ProtoReflect.Descriptor instead.
func (*EnqueueReplayJobRequest) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueueReplayJobRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EnqueueReplayJobRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *EnqueueReplayJobRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EnqueueReplayJobRequest) GetAdminReason() string {
	if x != nil {
		return x.AdminReason
	}
	return ""
}

type GetReplayJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplayJobRequest) Reset() {
	*x = GetReplayJobRequest{}
	mi := &file_tap_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplayJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplayJobRequest) ProtoMessage() {}

func (x *GetReplayJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplayJobRequest.ProtoReflect.Descriptor instead.
func (*GetReplayJobRequest) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *GetReplayJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelReplayJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AdminReason   string                 `protobuf:"bytes,2,opt,name=admin_reason,json=adminReason,proto3" json:"admin_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReplayJobRequest) Reset() {
	*x = CancelReplayJobRequest{}
	mi := &file_tap_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReplayJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReplayJobRequest) ProtoMessage() {}

func (x *CancelReplayJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReplayJobRequest.ProtoReflect.Descriptor instead.
func (*CancelReplayJobRequest) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *CancelReplayJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelReplayJobRequest) GetAdminReason() string {
	if x != nil {
		return x.AdminReason
	}
	return ""
}

type EnqueueReplayJobResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IdempotencyReused bool                   `protobuf:"varint,2,opt,name=idempotency_reused,json=idempotencyReused,proto3" json:"idempotency_reused,omitempty"`
	Job               *ReplayJob             `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnqueueReplayJobResponse) Reset() {
	*x = EnqueueReplayJobResponse{}
	mi := &file_tap_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueReplayJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueReplayJobResponse) ProtoMessage() {}

func (x *EnqueueReplayJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueReplayJobResponse.ProtoReflect.Descriptor instead.
func (*EnqueueReplayJobResponse) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *EnqueueReplayJobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EnqueueReplayJobResponse) GetIdempotencyReused() bool {
	if x != nil {
		return x.IdempotencyReused
	}
	return false
}

func (x *EnqueueReplayJobResponse) GetJob() *ReplayJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetPollerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollerStatusRequest) Reset() {
	*x = GetPollerStatusRequest{}
	mi := &file_tap_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollerStatusRequest) ProtoMessage() {}

func (x *GetPollerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPollerStatusRequest) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *GetPollerStatusRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetPollerStatusRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

type GetReplayJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Job           *ReplayJob             `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplayJobResponse) Reset() {
	*x = GetReplayJobResponse{}
	mi := &file_tap_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplayJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplayJobResponse) ProtoMessage() {}

func (x *GetReplayJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplayJobResponse.ProtoReflect.Descriptor instead.
func (*GetReplayJobResponse) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *GetReplayJobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetReplayJobResponse) GetJob() *ReplayJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type CancelReplayJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Job           *ReplayJob             `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReplayJobResponse) Reset() {
	*x = CancelReplayJobResponse{}
	mi := &file_tap_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReplayJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReplayJobResponse) ProtoMessage() {}

func (x *CancelReplayJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReplayJobResponse.ProtoReflect.Descriptor instead.
func (*CancelReplayJobResponse) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *CancelReplayJobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelReplayJobResponse) GetJob() *ReplayJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetPollerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Pollers       []*PollerStatus        `protobuf:"bytes,6,rep,name=pollers,proto3" json:"pollers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollerStatusResponse) Reset() {
	*x = GetPollerStatusResponse{}
	mi := &file_tap_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollerStatusResponse) ProtoMessage() {}

func (x *GetPollerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPollerStatusResponse) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetPollerStatusResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *GetPollerStatusResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetPollerStatusResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetPollerStatusResponse) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GetPollerStatusResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetPollerStatusResponse) GetPollers() []*PollerStatus {
	if x != nil {
		return x.Pollers
	}
	return nil
}

type PollerStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Provider             string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	TenantId             string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Interval             string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	RateLimitPerSec      float64                `protobuf:"fixed64,4,opt,name=rate_limit_per_sec,json=rateLimitPerSec,proto3" json:"rate_limit_per_sec,omitempty"`
	Burst                int32                  `protobuf:"varint,5,opt,name=burst,proto3" json:"burst,omitempty"`
	FailureBudget        int32                  `protobuf:"varint,6,opt,name=failure_budget,json=failureBudget,proto3" json:"failure_budget,omitempty"`
	CircuitBreakDuration string                 `protobuf:"bytes,7,opt,name=circuit_break_duration,json=circuitBreakDuration,proto3" json:"circuit_break_duration,omitempty"`
	JitterRatio          float64                `protobuf:"fixed64,8,opt,name=jitter_ratio,json=jitterRatio,proto3" json:"jitter_ratio,omitempty"`
	LastRunAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	LastSuccessAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	LastErrorAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_error_at,json=lastErrorAt,proto3" json:"last_error_at,omitempty"`
	LastError            string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastCheckpoint       string                 `protobuf:"bytes,13,opt,name=last_checkpoint,json=lastCheckpoint,proto3" json:"last_checkpoint,omitempty"`
	ConsecutiveFailures  int32                  `protobuf:"varint,14,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PollerStatus) Reset() {
	*x = PollerStatus{}
	mi := &file_tap_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollerStatus) ProtoMessage() {}

func (x *PollerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollerStatus.ProtoReflect.Descriptor instead.
func (*PollerStatus) Descriptor() ([]byte, []int) {
	return file_tap_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *PollerStatus) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PollerStatus) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PollerStatus) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *PollerStatus) GetRateLimitPerSec() float64 {
	if x != nil {
		return x.RateLimitPerSec
	}
	return 0
}

func (x *PollerStatus) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *PollerStatus) GetFailureBudget() int32 {
	if x != nil {
		return x.FailureBudget
	}
	return 0
}

func (x *PollerStatus) GetCircuitBreakDuration() string {
	if x != nil {
		return x.CircuitBreakDuration
	}
	return ""
}

func (x *PollerStatus) GetJitterRatio() float64 {
	if x != nil {
		return x.JitterRatio
	}
	return 0
}

func (x *PollerStatus) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *PollerStatus) GetLastSuccessAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessAt
	}
	return nil
}

func (x *PollerStatus) GetLastErrorAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastErrorAt
	}
	return nil
}

func (x *PollerStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *PollerStatus) GetLastCheckpoint() string {
	if x != nil {
		return x.LastCheckpoint
	}
	return ""
}

func (x *PollerStatus) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

var File_tap_v1_admin_proto protoreflect.FileDescriptor

const file_tap_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x12tap/v1/admin.proto\x12\x06tap.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x04\n" +
	"\tReplayJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.tap.v1.ReplayJobStatusR\x06status\x12'\n" +
	"\x0frequested_limit\x18\x03 \x01(\x05R\x0erequestedLimit\x12'\n" +
	"\x0feffective_limit\x18\x04 \x01(\x05R\x0eeffectiveLimit\x12\x1b\n" +
	"\tmax_limit\x18\x05 \x01(\x05R\bmaxLimit\x12\x16\n" +
	"\x06capped\x18\x06 \x01(\bR\x06capped\x12\x17\n" +
	"\adry_run\x18\a \x01(\bR\x06dryRun\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1a\n" +
	"\breplayed\x18\v \x01(\x05R\breplayed\x12\x1d\n" +
	"\n" +
	"request_id\x18\f \x01(\tR\trequestId\x12'\n" +
	"\x0foperator_reason\x18\r \x01(\tR\x0eoperatorReason\x12#\n" +
	"\rcancel_reason\x18\x0e \x01(\tR\fcancelReason\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\"]\n" +
	"\x14ReplayJobStatusCount\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.tap.v1.ReplayJobStatusR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"v\n" +
	"\x15ListReplayJobsRequest\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.tap.v1.ReplayJobStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xac\x02\n" +
	"\x16ListReplayJobsResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.tap.v1.ReplayJobStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1f\n" +
	"\vnext_cursor\x18\x05 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x05R\x05count\x126\n" +
	"\asummary\x18\a \x03(\v2\x1c.tap.v1.ReplayJobStatusCountR\asummary\x12%\n" +
	"\x04jobs\x18\b \x03(\v2\x11.tap.v1.ReplayJobR\x04jobs\"\x94\x01\n" +
	"\x17EnqueueReplayJobRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\fadmin_reason\x18\x04 \x01(\tR\vadminReason\",\n" +
	"\x13GetReplayJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"R\n" +
	"\x16CancelReplayJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fadmin_reason\x18\x02 \x01(\tR\vadminReason\"\x8d\x01\n" +
	"\x18EnqueueReplayJobResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12-\n" +
	"\x12idempotency_reused\x18\x02 \x01(\bR\x11idempotencyReused\x12#\n" +
	"\x03job\x18\x03 \x01(\v2\x11.tap.v1.ReplayJobR\x03job\"L\n" +
	"\x16GetPollerStatusRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\"Z\n" +
	"\x14GetReplayJobResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\x03job\x18\x02 \x01(\v2\x11.tap.v1.ReplayJobR\x03job\"]\n" +
	"\x17CancelReplayJobResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\x03job\x18\x02 \x01(\v2\x11.tap.v1.ReplayJobR\x03job\"\xf1\x01\n" +
	"\x17GetPollerStatusResponse\x12=\n" +
	"\fgenerated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\x12.\n" +
	"\apollers\x18\x06 \x03(\v2\x14.tap.v1.PollerStatusR\apollers\"\xe1\x04\n" +
	"\fPollerStatus\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\x12+\n" +
	"\x12rate_limit_per_sec\x18\x04 \x01(\x01R\x0frateLimitPerSec\x12\x14\n" +
	"\x05burst\x18\x05 \x01(\x05R\x05burst\x12%\n" +
	"\x0efailure_budget\x18\x06 \x01(\x05R\rfailureBudget\x124\n" +
	"\x16circuit_break_duration\x18\a \x01(\tR\x14circuitBreakDuration\x12!\n" +
	"\fjitter_ratio\x18\b \x01(\x01R\vjitterRatio\x12:\n" +
	"\vlast_run_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12B\n" +
	"\x0flast_success_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rlastSuccessAt\x12>\n" +
	"\rlast_error_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastErrorAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12'\n" +
	"\x0flast_checkpoint\x18\r \x01(\tR\x0elastCheckpoint\x121\n" +
	"\x14consecutive_failures\x18\x0e \x01(\x05R\x13consecutiveFailures*\xd1\x01\n" +
	"\x0fReplayJobStatus\x12!\n" +
	"\x1dREPLAY_JOB_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REPLAY_JOB_STATUS_QUEUED\x10\x01\x12\x1d\n" +
	"\x19REPLAY_JOB_STATUS_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bREPLAY_JOB_STATUS_SUCCEEDED\x10\x03\x12\x1c\n" +
	"\x18REPLAY_JOB_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bREPLAY_JOB_STATUS_CANCELLED\x10\x052\xac\x03\n" +
	"\x0fTapAdminService\x12O\n" +
	"\x0eListReplayJobs\x12\x1d.tap.v1.ListReplayJobsRequest\x1a\x1e.tap.v1.ListReplayJobsResponse\x12U\n" +
	"\x10EnqueueReplayJob\x12\x1f.tap.v1.EnqueueReplayJobRequest\x1a .tap.v1.EnqueueReplayJobResponse\x12I\n" +
	"\fGetReplayJob\x12\x1b.tap.v1.GetReplayJobRequest\x1a\x1c.tap.v1.GetReplayJobResponse\x12R\n" +
	"\x0fCancelReplayJob\x12\x1e.tap.v1.CancelReplayJobRequest\x1a\x1f.tap.v1.CancelReplayJobResponse\x12R\n" +
	"\x0fGetPollerStatus\x12\x1e.tap.v1.GetPollerStatusRequest\x1a\x1f.tap.v1.GetPollerStatusResponseB.Z,github.com/evalops/siphon/proto/tap/v1;tapv1b\x06proto3"

var (
	file_tap_v1_admin_proto_rawDescOnce sync.Once
	file_tap_v1_admin_proto_rawDescData []byte
)

func file_tap_v1_admin_proto_rawDescGZIP() []byte {
	file_tap_v1_admin_proto_rawDescOnce.Do(func() {
		file_tap_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tap_v1_admin_proto_rawDesc), len(file_tap_v1_admin_proto_rawDesc)))
	})
	return file_tap_v1_admin_proto_rawDescData
}

var file_tap_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tap_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tap_v1_admin_proto_goTypes = []any{
	(ReplayJobStatus)(0),             // 0: tap.v1.ReplayJobStatus
	(*ReplayJob)(nil),                // 1: tap.v1.ReplayJob
	(*ReplayJobStatusCount)(nil),     // 2: tap.v1.ReplayJobStatusCount
	(*ListReplayJobsRequest)(nil),    // 3: tap.v1.ListReplayJobsRequest
	(*ListReplayJobsResponse)(nil),   // 4: tap.v1.ListReplayJobsResponse
	(*EnqueueReplayJobRequest)(nil),  // 5: tap.v1.EnqueueReplayJobRequest
	(*GetReplayJobRequest)(nil),      // 6: tap.v1.GetReplayJobRequest
	(*CancelReplayJobRequest)(nil),   // 7: tap.v1.CancelReplayJobRequest
	(*EnqueueReplayJobResponse)(nil), // 8: tap.v1.EnqueueReplayJobResponse
	(*GetPollerStatusRequest)(nil),   // 9: tap.v1.GetPollerStatusRequest
	(*GetReplayJobResponse)(nil),     // 10: tap.v1.GetReplayJobResponse
	(*CancelReplayJobResponse)(nil),  // 11: tap.v1.CancelReplayJobResponse
	(*GetPollerStatusResponse)(nil),  // 12: tap.v1.GetPollerStatusResponse
	(*PollerStatus)(nil),             // 13: tap.v1.PollerStatus
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
}
var file_tap_v1_admin_proto_depIdxs = []int32{
	0,  // 0: tap.v1.ReplayJob.status:type_name -> tap.v1.ReplayJobStatus
	14, // 1: tap.v1.ReplayJob.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: tap.v1.ReplayJob.started_at:type_name -> google.protobuf.Timestamp
	14, // 3: tap.v1.ReplayJob.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 4: tap.v1.ReplayJobStatusCount.status:type_name -> tap.v1.ReplayJobStatus
	0,  // 5: tap.v1.ListReplayJobsRequest.status:type_name -> tap.v1.ReplayJobStatus
	0,  // 6: tap.v1.ListReplayJobsResponse.status:type_name -> tap.v1.ReplayJobStatus
	2,  // 7: tap.v1.ListReplayJobsResponse.summary:type_name -> tap.v1.ReplayJobStatusCount
	1,  // 8: tap.v1.ListReplayJobsResponse.jobs:type_name -> tap.v1.ReplayJob
	1,  // 9: tap.v1.EnqueueReplayJobResponse.job:type_name -> tap.v1.ReplayJob
	1,  // 10: tap.v1.GetReplayJobResponse.job:type_name -> tap.v1.ReplayJob
	1,  // 11: tap.v1.CancelReplayJobResponse.job:type_name -> tap.v1.ReplayJob
	14, // 12: tap.v1.GetPollerStatusResponse.generated_at:type_name -> google.protobuf.Timestamp
	13, // 13: tap.v1.GetPollerStatusResponse.pollers:type_name -> tap.v1.PollerStatus
	14, // 14: tap.v1.PollerStatus.last_run_at:type_name -> google.protobuf.Timestamp
	14, // 15: tap.v1.PollerStatus.last_success_at:type_name -> google.protobuf.Timestamp
	14, // 16: tap.v1.PollerStatus.last_error_at:type_name -> google.protobuf.Timestamp
	3,  // 17: tap.v1.TapAdminService.ListReplayJobs:input_type -> tap.v1.ListReplayJobsRequest
	5,  // 18: tap.v1.TapAdminService.EnqueueReplayJob:input_type -> tap.v1.EnqueueReplayJobRequest
	6,  // 19: tap.v1.TapAdminService.GetReplayJob:input_type -> tap.v1.GetReplayJobRequest
	7,  // 20: tap.v1.TapAdminService.CancelReplayJob:input_type -> tap.v1.CancelReplayJobRequest
	9,  // 21: tap.v1.TapAdminService.GetPollerStatus:input_type -> tap.v1.GetPollerStatusRequest
	4,  // 22: tap.v1.TapAdminService.ListReplayJobs:output_type -> tap.v1.ListReplayJobsResponse
	8,  // 23: tap.v1.TapAdminService.EnqueueReplayJob:output_type -> tap.v1.EnqueueReplayJobResponse
	10, // 24: tap.v1.TapAdminService.GetReplayJob:output_type -> tap.v1.GetReplayJobResponse
	11, // 25: tap.v1.TapAdminService.CancelReplayJob:output_type -> tap.v1.CancelReplayJobResponse
	12, // 26: tap.v1.TapAdminService.GetPollerStatus:output_type -> tap.v1.GetPollerStatusResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_tap_v1_admin_proto_init() }
func file_tap_v1_admin_proto_init() {
	if File_tap_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tap_v1_admin_proto_rawDesc), len(file_tap_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tap_v1_admin_proto_goTypes,
		DependencyIndexes: file_tap_v1_admin_proto_depIdxs,
		EnumInfos:         file_tap_v1_admin_proto_enumTypes,
		MessageInfos:      file_tap_v1_admin_proto_msgTypes,
	}.Build()
	File_tap_v1_admin_proto = out.File
	file_tap_v1_admin_proto_goTypes = nil
	file_tap_v1_admin_proto_depIdxs = nil
}
