// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tap/v1/event.proto

package tapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *structpb.Value        `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *structpb.Value        `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldChange) Reset() {
	*x = FieldChange{}
	mi := &file_tap_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldChange) ProtoMessage() {}

func (x *FieldChange) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldChange.ProtoReflect.Descriptor instead.
func (*FieldChange) Descriptor() ([]byte, []int) {
	return file_tap_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *FieldChange) GetFrom() *structpb.Value {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FieldChange) GetTo() *structpb.Value {
	if x != nil {
		return x.To
	}
	return nil
}

type TapEventData struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Provider          string                  `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	EntityType        string                  `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId          string                  `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action            string                  `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Changes           map[string]*FieldChange `protobuf:"bytes,5,rep,name=changes,proto3" json:"changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Snapshot          *structpb.Struct        `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	ProviderEventId   string                  `protobuf:"bytes,7,opt,name=provider_event_id,json=providerEventId,proto3" json:"provider_event_id,omitempty"`
	ProviderTimestamp string                  `protobuf:"bytes,8,opt,name=provider_timestamp,json=providerTimestamp,proto3" json:"provider_timestamp,omitempty"`
	TenantId          string                  `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RequestId         string                  `protobuf:"bytes,10,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TapEventData) Reset() {
	*x = TapEventData{}
	mi := &file_tap_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapEventData) ProtoMessage() {}

func (x *TapEventData) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapEventData.ProtoReflect.Descriptor instead.
func (*TapEventData) Descriptor() ([]byte, []int) {
	return file_tap_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *TapEventData) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TapEventData) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *TapEventData) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *TapEventData) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TapEventData) GetChanges() map[string]*FieldChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *TapEventData) GetSnapshot() *structpb.Struct {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *TapEventData) GetProviderEventId() string {
	if x != nil {
		return x.ProviderEventId
	}
	return ""
}

func (x *TapEventData) GetProviderTimestamp() string {
	if x != nil {
		return x.ProviderTimestamp
	}
	return ""
}

func (x *TapEventData) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TapEventData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type NormalizedEvent struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Provider        string                  `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	EntityType      string                  `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId        string                  `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action          string                  `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ProviderEventId string                  `protobuf:"bytes,5,opt,name=provider_event_id,json=providerEventId,proto3" json:"provider_event_id,omitempty"`
	ProviderTime    *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=provider_time,json=providerTime,proto3" json:"provider_time,omitempty"`
	TenantId        string                  `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RequestId       string                  `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Changes         map[string]*FieldChange `protobuf:"bytes,9,rep,name=changes,proto3" json:"changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Snapshot        *structpb.Struct        `protobuf:"bytes,10,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NormalizedEvent) Reset() {
	*x = NormalizedEvent{}
	mi := &file_tap_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedEvent) ProtoMessage() {}

func (x *NormalizedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tap_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedEvent.ProtoReflect.Descriptor instead.
func (*NormalizedEvent) Descriptor() ([]byte, []int) {
	return file_tap_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *NormalizedEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *NormalizedEvent) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *NormalizedEvent) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *NormalizedEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *NormalizedEvent) GetProviderEventId() string {
	if x != nil {
		return x.ProviderEventId
	}
	return ""
}

func (x *NormalizedEvent) GetProviderTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ProviderTime
	}
	return nil
}

func (x *NormalizedEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NormalizedEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NormalizedEvent) GetChanges() map[string]*FieldChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *NormalizedEvent) GetSnapshot() *structpb.Struct {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_tap_v1_event_proto protoreflect.FileDescriptor

const file_tap_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x12tap/v1/event.proto\x12\x06tap.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\vFieldChange\x12*\n" +
	"\x04from\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x04from\x12&\n" +
	"\x02to\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x02to\"\xda\x03\n" +
	"\fTapEventData\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12;\n" +
	"\achanges\x18\x05 \x03(\v2!.tap.v1.TapEventData.ChangesEntryR\achanges\x123\n" +
	"\bsnapshot\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bsnapshot\x12*\n" +
	"\x11provider_event_id\x18\a \x01(\tR\x0fproviderEventId\x12-\n" +
	"\x12provider_timestamp\x18\b \x01(\tR\x11providerTimestamp\x12\x1b\n" +
	"\ttenant_id\x18\t \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"request_id\x18\n" +
	" \x01(\tR\trequestId\x1aO\n" +
	"\fChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tap.v1.FieldChangeR\x05value:\x028\x01\"\xf2\x03\n" +
	"\x0fNormalizedEvent\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12*\n" +
	"\x11provider_event_id\x18\x05 \x01(\tR\x0fproviderEventId\x12?\n" +
	"\rprovider_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fproviderTime\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12>\n" +
	"\achanges\x18\t \x03(\v2$.tap.v1.NormalizedEvent.ChangesEntryR\achanges\x123\n" +
	"\bsnapshot\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bsnapshot\x1aO\n" +
	"\fChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tap.v1.FieldChangeR\x05value:\x028\x01B.Z,github.com/evalops/siphon/proto/tap/v1;tapv1b\x06proto3"

var (
	file_tap_v1_event_proto_rawDescOnce sync.Once
	file_tap_v1_event_proto_rawDescData []byte
)

func file_tap_v1_event_proto_rawDescGZIP() []byte {
	file_tap_v1_event_proto_rawDescOnce.Do(func() {
		file_tap_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tap_v1_event_proto_rawDesc), len(file_tap_v1_event_proto_rawDesc)))
	})
	return file_tap_v1_event_proto_rawDescData
}

var file_tap_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tap_v1_event_proto_goTypes = []any{
	(*FieldChange)(nil),           // 0: tap.v1.FieldChange
	(*TapEventData)(nil),          // 1: tap.v1.TapEventData
	(*NormalizedEvent)(nil),       // 2: tap.v1.NormalizedEvent
	nil,                           // 3: tap.v1.TapEventData.ChangesEntry
	nil,                           // 4: tap.v1.NormalizedEvent.ChangesEntry
	(*structpb.Value)(nil),        // 5: google.protobuf.Value
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_tap_v1_event_proto_depIdxs = []int32{
	5, // 0: tap.v1.FieldChange.from:type_name -> google.protobuf.Value
	5, // 1: tap.v1.FieldChange.to:type_name -> google.protobuf.Value
	3, // 2: tap.v1.TapEventData.changes:type_name -> tap.v1.TapEventData.ChangesEntry
	6, // 3: tap.v1.TapEventData.snapshot:type_name -> google.protobuf.Struct
	7, // 4: tap.v1.NormalizedEvent.provider_time:type_name -> google.protobuf.Timestamp
	4, // 5: tap.v1.NormalizedEvent.changes:type_name -> tap.v1.NormalizedEvent.ChangesEntry
	6, // 6: tap.v1.NormalizedEvent.snapshot:type_name -> google.protobuf.Struct
	0, // 7: tap.v1.TapEventData.ChangesEntry.value:type_name -> tap.v1.FieldChange
	0, // 8: tap.v1.NormalizedEvent.ChangesEntry.value:type_name -> tap.v1.FieldChange
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_tap_v1_event_proto_init() }
func file_tap_v1_event_proto_init() {
	if File_tap_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tap_v1_event_proto_rawDesc), len(file_tap_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tap_v1_event_proto_goTypes,
		DependencyIndexes: file_tap_v1_event_proto_depIdxs,
		MessageInfos:      file_tap_v1_event_proto_msgTypes,
	}.Build()
	File_tap_v1_event_proto = out.File
	file_tap_v1_event_proto_goTypes = nil
	file_tap_v1_event_proto_depIdxs = nil
}
